import { db } from "./db";
import { readingPassages, readingQuestions, listeningPassages, listeningQuestions, writingPrompts, speakingPrompts } from "@shared/schema";

const readingTopics = [
  { title: "The Rise of Remote Work", category: "Society & Work", difficulty: "Intermediate",
    content: "The COVID-19 pandemic fundamentally transformed how millions of people work. What began as an emergency measure quickly evolved into a lasting shift in workplace culture. Surveys indicated that over 40% of knowledge workers continued to work remotely at least part-time. Companies initially worried about productivity declines. However, research found that remote workers were actually 13% more productive than their office-based counterparts. The shift has not been without challenges. Many workers report feeling isolated. Cities have also felt the impact with commercial real estate markets seeing vacancy rates climb." },
  { title: "Climate Change and Agriculture", category: "Environment", difficulty: "Advanced",
    content: "Global warming presents unprecedented challenges for agriculture worldwide. Rising temperatures alter growing seasons, while changing precipitation patterns affect crop yields. Scientists predict that wheat production could decline by 6% for each degree Celsius of temperature increase. Developing nations face the greatest risks as many rely heavily on rain-fed agriculture. Adaptation strategies include drought-resistant crop varieties, improved irrigation techniques, and shifting planting schedules. Carbon sequestration through regenerative farming practices offers a potential solution that addresses both food security and climate mitigation simultaneously." },
  { title: "Artificial Intelligence in Healthcare", category: "Technology", difficulty: "Intermediate",
    content: "Artificial intelligence is revolutionizing healthcare delivery across the globe. Machine learning algorithms can now detect diseases from medical images with accuracy rivaling experienced radiologists. Natural language processing helps extract insights from patient records. AI-powered drug discovery has accelerated the development of new treatments. However, concerns about data privacy, algorithmic bias, and the doctor-patient relationship persist. Regulatory frameworks struggle to keep pace with technological advancement. The integration of AI in healthcare requires careful balance between innovation and patient safety." },
  { title: "Ocean Plastic Pollution", category: "Environment", difficulty: "Beginner",
    content: "Every year, approximately 8 million tons of plastic waste enters the world's oceans. This pollution affects marine ecosystems at every level, from microscopic organisms to large whales. Microplastics have been found in drinking water, seafood, and even human blood. Countries are implementing various strategies including plastic bag bans, bottle deposit schemes, and improved waste management infrastructure. Cleanup technologies such as ocean booms and autonomous collection vessels show promise but cannot keep pace with the rate of pollution. Prevention through reducing plastic consumption remains the most effective approach." },
  { title: "The Psychology of Decision Making", category: "Psychology", difficulty: "Advanced",
    content: "Human decision-making is far less rational than we like to believe. Cognitive biases systematically distort our judgment in predictable ways. The anchoring effect causes us to rely too heavily on the first piece of information we encounter. Confirmation bias leads us to seek information that supports our existing beliefs while ignoring contradictory evidence. Loss aversion makes us feel losses approximately twice as intensely as equivalent gains. Understanding these biases has practical applications in fields ranging from marketing to public policy. Behavioral economists have developed 'nudge' strategies that harness these biases to encourage better decisions." },
  { title: "Renewable Energy Revolution", category: "Technology", difficulty: "Intermediate",
    content: "The transition to renewable energy sources is accelerating at an unprecedented pace. Solar panel costs have dropped by over 90% since 2010, making solar power the cheapest form of electricity generation in many regions. Wind energy capacity has grown exponentially, with offshore wind farms becoming increasingly common. Battery storage technology is addressing the intermittency challenge that has long limited renewable adoption. Countries like Denmark, Portugal, and Costa Rica have demonstrated that high percentages of renewable electricity are achievable. The economic case for clean energy now often surpasses traditional fossil fuels." },
  { title: "Urbanization and Megacities", category: "Society & Work", difficulty: "Intermediate",
    content: "By 2050, nearly 70% of the world's population will live in urban areas. Megacities with populations exceeding 10 million are growing rapidly, particularly in Asia and Africa. This urban growth creates both opportunities and challenges. Cities drive economic productivity and innovation but also face issues of overcrowding, pollution, and inequality. Smart city technologies offer potential solutions through efficient resource management. Urban planning must balance density with livability, incorporating green spaces and sustainable transportation. The concept of the 15-minute city, where daily necessities are within walking distance, is gaining traction globally." },
  { title: "The Gut Microbiome", category: "Science", difficulty: "Advanced",
    content: "The human gut contains trillions of microorganisms that play crucial roles in health and disease. Research has revealed connections between gut bacteria and conditions ranging from obesity to depression. The microbiome influences immune function, nutrient absorption, and even brain chemistry through the gut-brain axis. Diet significantly impacts microbiome composition, with fiber-rich diets promoting beneficial bacteria diversity. Antibiotics can disrupt this delicate ecosystem, sometimes with lasting consequences. Fecal microbiota transplantation has emerged as a treatment for recurrent infections. Personalized nutrition based on individual microbiome profiles represents a promising frontier." },
  { title: "Space Exploration and Colonization", category: "Science", difficulty: "Intermediate",
    content: "Humanity stands on the threshold of becoming a multi-planetary species. NASA's Artemis program aims to return humans to the Moon, while SpaceX develops vehicles for Mars colonization. The International Space Station has demonstrated that humans can live in space for extended periods. However, numerous challenges remain including radiation exposure, bone density loss, and psychological stress from isolation. Resource extraction from asteroids could fund future missions while reducing strain on Earth's resources. The debate between robotic and crewed exploration continues, with proponents arguing that human adaptability remains unmatched by current technology." },
  { title: "Digital Privacy in the Modern Age", category: "Technology", difficulty: "Intermediate",
    content: "In an era of ubiquitous connectivity, digital privacy has become a paramount concern. Social media platforms collect vast amounts of personal data, often with minimal user awareness. Data breaches expose millions of records annually, creating risks of identity theft and fraud. Regulations like GDPR in Europe and CCPA in California represent legislative responses to these challenges. Encryption technologies protect communications but face opposition from law enforcement agencies. The tension between security and privacy continues to shape public discourse. Individuals increasingly adopt tools like VPNs and privacy-focused browsers to protect their digital footprint." },
  { title: "The Future of Education", category: "Education", difficulty: "Beginner",
    content: "Traditional classroom education is undergoing rapid transformation. Online learning platforms have made quality education accessible to millions worldwide. Personalized learning powered by AI adapts to individual student pace and style. Gamification increases engagement and motivation among learners. However, the digital divide means that not all students have equal access to technology. Social skills development and peer interaction remain important aspects that virtual learning cannot fully replicate. Hybrid models combining online and in-person instruction may offer the best of both worlds. Lifelong learning is becoming essential as career requirements evolve rapidly." },
  { title: "Biodiversity Loss and Conservation", category: "Environment", difficulty: "Advanced",
    content: "The Earth is experiencing its sixth mass extinction event, driven primarily by human activities. Habitat destruction, overexploitation, pollution, and climate change threaten millions of species. Scientists estimate that species are going extinct at 1,000 times the natural background rate. Protected areas cover approximately 15% of Earth's land surface but often lack adequate funding and enforcement. Conservation genetics helps identify and preserve genetic diversity within populations. Community-based conservation programs that involve indigenous peoples have shown particular success. The economic value of ecosystem services provided by biodiversity runs into trillions of dollars annually." },
  { title: "Sleep Science and Health", category: "Science", difficulty: "Beginner",
    content: "Sleep is essential for physical and mental health, yet millions of people worldwide are chronically sleep-deprived. Adults need seven to nine hours of sleep per night for optimal functioning. During sleep, the brain consolidates memories, clears waste products, and repairs tissues. Chronic sleep deprivation increases the risk of heart disease, diabetes, obesity, and mental health disorders. Blue light from screens disrupts melatonin production, making it harder to fall asleep. Good sleep hygiene practices include maintaining a consistent schedule, creating a dark and cool environment, and avoiding caffeine in the afternoon." },
  { title: "The Economics of Inequality", category: "Society & Work", difficulty: "Advanced",
    content: "Income inequality has widened significantly in many countries over the past four decades. The richest 1% now own more wealth than the bottom 50% combined globally. This concentration of wealth has implications for social mobility, health outcomes, and political stability. Technological change and globalization have contributed to wage stagnation for middle-class workers while boosting returns for capital owners. Progressive taxation, universal basic income, and improved access to education are among proposed solutions. The debate between market efficiency and equitable distribution remains central to economic policy discussions worldwide." },
  { title: "Water Scarcity Crisis", category: "Environment", difficulty: "Intermediate",
    content: "Freshwater scarcity affects over two billion people worldwide and is projected to worsen with climate change and population growth. Agriculture accounts for approximately 70% of global freshwater withdrawals. Inefficient irrigation methods waste enormous quantities of water. Desalination technology offers a potential solution for coastal regions but requires significant energy input. Water recycling and rainwater harvesting can supplement traditional supplies. Transboundary water disputes create geopolitical tensions in regions like the Middle East and Central Asia. Pricing water to reflect its true value could encourage conservation without disadvantaging vulnerable populations." },
  { title: "Genetic Engineering Ethics", category: "Science", difficulty: "Advanced",
    content: "CRISPR gene editing technology has opened unprecedented possibilities for modifying living organisms. Scientists can now correct genetic mutations that cause diseases like sickle cell anemia and cystic fibrosis. However, the ability to edit human embryos raises profound ethical questions about designer babies and genetic inequality. Agricultural applications include developing drought-resistant crops and disease-immune livestock. Gene drives could theoretically eliminate disease-carrying mosquito populations but pose ecological risks. International regulations vary widely, creating concerns about genetic tourism. The line between therapy and enhancement remains contentious among bioethicists." },
  { title: "The Sharing Economy", category: "Society & Work", difficulty: "Beginner",
    content: "Platforms like Uber, Airbnb, and TaskRabbit have transformed how people access services and earn income. The sharing economy enables individuals to monetize underutilized assets such as cars, homes, and skills. Proponents argue it increases economic efficiency and provides flexible employment opportunities. Critics raise concerns about labor rights, safety standards, and the disruption of established industries. Regulatory frameworks struggle to classify gig workers as employees or independent contractors. The pandemic accelerated some sharing economy trends while challenging others. Trust and rating systems serve as the foundation for transactions between strangers." },
  { title: "Mental Health Awareness", category: "Psychology", difficulty: "Beginner",
    content: "Mental health conditions affect approximately one in four people globally at some point in their lives. Depression is the leading cause of disability worldwide. Despite growing awareness, stigma surrounding mental illness persists in many cultures. Access to mental health services remains inadequate, particularly in low-income countries where there may be fewer than one psychiatrist per million people. Digital mental health tools, including therapy apps and online counseling, are expanding access. Workplace mental health programs show positive returns on investment through reduced absenteeism and improved productivity. Early intervention is crucial for better outcomes." },
  { title: "Autonomous Vehicles", category: "Technology", difficulty: "Intermediate",
    content: "Self-driving cars represent one of the most transformative technologies in development today. Major companies including Tesla, Waymo, and Cruise are testing autonomous vehicles on public roads. The technology promises to reduce accidents caused by human error, which account for over 90% of traffic incidents. However, edge cases and unpredictable scenarios remain challenging for current AI systems. The ethical dilemma of how autonomous vehicles should prioritize safety in unavoidable accident scenarios raises philosophical questions. Infrastructure changes including dedicated lanes and smart traffic signals will be necessary. The transition period of mixed human and autonomous traffic presents unique risks." },
  { title: "Coral Reef Ecosystems", category: "Environment", difficulty: "Intermediate",
    content: "Coral reefs support approximately 25% of all marine species despite covering less than 1% of the ocean floor. Rising ocean temperatures cause coral bleaching, a stress response that can lead to death if prolonged. The Great Barrier Reef has experienced multiple mass bleaching events in recent years. Ocean acidification from absorbed carbon dioxide further weakens coral structures. Reef restoration efforts including coral gardening and assisted evolution show promise on small scales. Marine protected areas help reduce local stressors like overfishing and pollution. Without significant action to address climate change, scientists predict that 70-90% of coral reefs could disappear by 2050." },
  { title: "The Gig Economy", category: "Society & Work", difficulty: "Intermediate",
    content: "The gig economy has fundamentally altered employment patterns across developed nations. Workers increasingly piece together multiple short-term contracts rather than holding traditional full-time positions. This shift offers flexibility but often lacks benefits like health insurance, retirement plans, and paid leave. Platform companies argue they provide opportunities for entrepreneurship and autonomy. Labor advocates push for gig workers to receive employee protections. Some jurisdictions have implemented legislation requiring platforms to reclassify workers. The long-term implications for social safety nets designed around traditional employment remain uncertain." },
  { title: "Food Security Challenges", category: "Society & Work", difficulty: "Intermediate",
    content: "Despite producing enough food to feed the global population, approximately 800 million people remain chronically hungry. Food waste accounts for roughly one-third of all food produced worldwide. Supply chain disruptions, conflict, and climate change exacerbate food insecurity in vulnerable regions. Vertical farming and lab-grown meat offer innovative solutions to increase food production sustainability. Genetic modification of crops can improve yields and nutritional content. Reducing food waste through improved storage, distribution, and consumer behavior change could significantly improve food security. International cooperation and equitable trade policies are essential for addressing global hunger." },
  { title: "Cryptocurrency and Blockchain", category: "Technology", difficulty: "Advanced",
    content: "Blockchain technology, initially developed for Bitcoin, has evolved into a platform with applications far beyond cryptocurrency. Decentralized finance protocols allow financial transactions without traditional intermediaries. Smart contracts automate complex business agreements. Non-fungible tokens have created new models for digital ownership and creative monetization. However, the energy consumption of proof-of-work mining raises environmental concerns. Regulatory uncertainty creates challenges for institutional adoption. Central bank digital currencies represent governments' response to private cryptocurrency growth. The volatility of crypto markets has led to significant financial losses for many individual investors." },
  { title: "Antibiotic Resistance", category: "Science", difficulty: "Advanced",
    content: "The World Health Organization has declared antibiotic resistance one of the greatest threats to global health. Overuse and misuse of antibiotics in human medicine and animal agriculture have accelerated the evolution of resistant bacteria. Infections that were once easily treatable are becoming deadly again. The development pipeline for new antibiotics has slowed as pharmaceutical companies find limited financial incentive. Phage therapy, which uses viruses that target specific bacteria, offers an alternative approach. Antimicrobial stewardship programs aim to optimize antibiotic prescribing practices. International coordination is essential as resistant bacteria do not respect national borders." },
  { title: "The Art of Persuasion", category: "Psychology", difficulty: "Intermediate",
    content: "Persuasion is a fundamental aspect of human communication that influences decisions in contexts from advertising to politics. Robert Cialdini identified six principles of influence: reciprocity, commitment, social proof, authority, liking, and scarcity. Understanding these principles helps both in crafting persuasive messages and in recognizing when others attempt to influence us. The rise of social media has created new channels for persuasion, including influencer marketing and algorithmically targeted advertising. Misinformation spreads more rapidly than accurate information online. Media literacy education helps individuals critically evaluate persuasive messages. Ethical persuasion respects audience autonomy while presenting compelling arguments." },
];

const readingQuestionTemplates = [
  { type: "main_idea", template: (t: string) => `What is the main idea of the passage about ${t}?`, options: (t: string) => [`The complete history of ${t}`, `Current challenges and opportunities related to ${t}`, `A personal opinion about ${t}`, `Statistical analysis of ${t}`], correct: 1 },
  { type: "detail", template: (t: string) => `According to the passage, which of the following is mentioned as a challenge?`, options: (_: string) => ["Excessive government support", "Lack of public interest", "Implementation difficulties and concerns", "Universal agreement among experts"], correct: 2 },
  { type: "inference", template: (t: string) => `What can be inferred from the passage?`, options: (_: string) => ["The situation is simple and straightforward", "Multiple factors contribute to the complexity of the issue", "Only one solution exists", "The problem has already been solved"], correct: 1 },
  { type: "vocab", template: (t: string) => `In the context of the passage, which word best describes the author's tone?`, options: (_: string) => ["Highly critical", "Informative and balanced", "Emotionally charged", "Humorous and light"], correct: 1 },
];

const listeningTopics = [
  { title: "University Lecture on Marine Biology", category: "Academic", difficulty: "Intermediate",
    transcript: "Good morning, everyone. Today we'll be discussing marine ecosystems and the role of keystone species. A keystone species is one that has a disproportionately large effect on its environment relative to its abundance. The classic example is the sea otter, which preys on sea urchins. Without sea otters, urchin populations explode and devour kelp forests. This phenomenon was first documented by Robert Paine in the 1960s. The concept has since been applied to terrestrial ecosystems as well. Understanding keystone species is crucial for conservation planning." },
  { title: "Radio Discussion on Urban Planning", category: "General", difficulty: "Beginner",
    transcript: "Welcome to City Talk. Today we're discussing the concept of walkable cities. Our guest, Dr. Sarah Chen, has spent twenty years studying urban mobility. Dr. Chen, what makes a city walkable? Well, it comes down to several factors: mixed-use zoning that puts homes near shops and offices, safe pedestrian infrastructure, and pleasant streetscapes with trees and lighting. Cities like Copenhagen and Amsterdam have shown that reducing car dependency improves quality of life, reduces pollution, and even boosts local economies." },
  { title: "Business Presentation on Market Trends", category: "Business", difficulty: "Advanced",
    transcript: "Thank you for joining this quarterly review. I'd like to highlight three key market trends we've identified. First, consumer preferences are shifting toward sustainable products, with 65% of respondents willing to pay more for eco-friendly options. Second, the subscription economy continues to grow at 18% annually. Third, personalization driven by artificial intelligence is becoming the standard expectation. Companies that fail to adapt to these trends risk losing market share. Let me walk you through our strategic response to each of these developments." },
  { title: "Museum Audio Guide: Ancient Egypt", category: "Cultural", difficulty: "Beginner",
    transcript: "Welcome to the Ancient Egypt gallery. The artifact before you is a canopic jar dating from the 18th Dynasty, approximately 1400 BCE. These jars were used during mummification to store and preserve the internal organs of the deceased. Four jars were typically used, each protected by a different deity. The liver was guarded by Imsety, the lungs by Hapi, the stomach by Duamutef, and the intestines by Qebehsenuef. This particular jar features an elaborately carved limestone lid and hieroglyphic inscriptions identifying its owner." },
  { title: "Podcast on Artificial Intelligence Ethics", category: "Technology", difficulty: "Advanced",
    transcript: "The question isn't whether AI will transform society, but how we ensure it does so fairly. Algorithmic bias has already been documented in criminal justice, hiring, and lending systems. When training data reflects historical inequalities, AI systems perpetuate and sometimes amplify these biases. Transparency in algorithm design and diverse development teams are essential safeguards. The European Union's AI Act represents the first comprehensive attempt to regulate artificial intelligence. However, balancing innovation with protection remains a significant challenge for policymakers worldwide." },
  { title: "Travel Documentary: Japanese Culture", category: "Cultural", difficulty: "Intermediate",
    transcript: "Japan's unique cultural traditions reflect centuries of isolation and careful cultivation. The tea ceremony, or chado, embodies the principles of harmony, respect, purity, and tranquility. Each movement is deliberate and meaningful, transforming a simple act of preparing tea into a meditative practice. Similarly, ikebana, the art of flower arrangement, emphasizes asymmetry and space as much as the flowers themselves. These aesthetic principles extend to architecture, garden design, and even cuisine, where presentation is considered as important as taste." },
  { title: "Health Seminar: Nutrition Myths", category: "Health", difficulty: "Beginner",
    transcript: "Let's debunk some common nutrition myths today. First, eating fat doesn't necessarily make you fat. Healthy fats from sources like avocados, nuts, and olive oil are essential for brain function and hormone production. Second, carbohydrates are not inherently bad. Whole grains, fruits, and vegetables provide crucial fiber and nutrients. Third, detox diets are largely unnecessary as your liver and kidneys already perform this function naturally. The key to good nutrition is balance, variety, and moderation rather than following restrictive diet trends." },
  { title: "Academic Debate on Free Trade", category: "Academic", difficulty: "Advanced",
    transcript: "The free trade debate has intensified in recent years with rising protectionist sentiment. Proponents argue that comparative advantage allows countries to specialize in what they produce most efficiently, lowering prices for consumers. Critics counter that free trade agreements have hollowed out manufacturing sectors in developed nations, leading to job losses and wage stagnation. The evidence suggests a nuanced picture where trade liberalization generates net economic gains but distributes them unevenly. Effective policy must therefore combine trade openness with domestic programs that support displaced workers." },
  { title: "Nature Documentary: Arctic Wildlife", category: "Nature", difficulty: "Intermediate",
    transcript: "The Arctic region, despite its harsh conditions, supports a remarkable diversity of life. Polar bears, the apex predators of this ecosystem, rely on sea ice to hunt ringed seals. As climate change reduces ice coverage, polar bears face increasing difficulty finding food. Arctic foxes demonstrate remarkable adaptations, changing their coat color from white in winter to brown in summer. Migratory species like the Arctic tern travel an astonishing 70,000 kilometers annually between the Arctic and Antarctic. The interconnectedness of Arctic species means that changes affecting one species ripple through the entire ecosystem." },
  { title: "Student Conversation: Study Abroad", category: "General", difficulty: "Beginner",
    transcript: "Hey, are you thinking about the study abroad program? Yeah, I'm really interested in the one in Barcelona. My advisor said it's great for language immersion. The application deadline is next month, and you need a minimum GPA of 3.0. The program covers tuition and housing but you need to arrange your own flights. I heard the classes are taught in both English and Spanish. That sounds perfect since I'm minoring in Spanish. Have you talked to anyone who's done it? Yes, my roommate went last year and said it was the best experience of her college life." },
  { title: "Environmental Conference Keynote", category: "Academic", difficulty: "Advanced",
    transcript: "Distinguished colleagues, we stand at a critical juncture in environmental policy. The latest IPCC report indicates we have less than a decade to halve global emissions if we are to limit warming to 1.5 degrees Celsius. The technologies we need largely exist already: renewable energy, electric vehicles, energy-efficient buildings, and sustainable agriculture. What we lack is the political will and economic incentives to deploy them at scale. Carbon pricing mechanisms, whether through carbon taxes or cap-and-trade systems, have proven effective where implemented. However, international cooperation remains insufficient." },
  { title: "Cooking Show: Mediterranean Diet", category: "Health", difficulty: "Beginner",
    transcript: "Today we're exploring the Mediterranean diet, which has been recognized by UNESCO as an intangible cultural heritage. This way of eating emphasizes fruits, vegetables, whole grains, legumes, nuts, and olive oil. Fish and seafood are consumed regularly, while red meat is limited to a few times per month. Studies consistently show that the Mediterranean diet reduces the risk of heart disease, diabetes, and certain cancers. The social aspect is equally important: meals are typically shared with family and friends, eaten slowly, and savored. Let me show you how to prepare a classic Greek salad." },
  { title: "Technology Conference: Cloud Computing", category: "Technology", difficulty: "Intermediate",
    transcript: "Cloud computing has fundamentally changed how businesses operate and scale. The three main service models are Infrastructure as a Service, Platform as a Service, and Software as a Service. Companies no longer need to maintain expensive on-premises servers. Instead, they can access computing resources on demand, paying only for what they use. Security remains a primary concern, with multi-cloud strategies becoming increasingly popular to avoid vendor lock-in. Edge computing is emerging as a complement to cloud services, processing data closer to where it's generated to reduce latency." },
  { title: "History Lecture: Industrial Revolution", category: "Academic", difficulty: "Intermediate",
    transcript: "The Industrial Revolution, which began in Britain in the late 18th century, was perhaps the most significant transformation in human history. The shift from agricultural to industrial economies was driven by several factors: availability of natural resources, particularly coal and iron; a stable political system; a growing consumer market; and a culture of innovation. The introduction of the steam engine, mechanical loom, and later the railway system transformed production, transportation, and daily life. However, this period also brought significant social upheaval, including child labor, urban poverty, and environmental degradation." },
  { title: "Interview: Olympic Athlete", category: "Sports", difficulty: "Beginner",
    transcript: "So tell us about your training routine. Well, I train about six hours a day, six days a week. My morning starts at 5 AM with a two-hour swimming session. After breakfast, I do strength training for about an hour. In the afternoon, I have another pool session focusing on technique. Nutrition is incredibly important too. I work with a sports dietitian who plans every meal. The mental aspect is often overlooked. I work with a sports psychologist to handle competition pressure and visualization techniques. It's not just about physical ability; the mental game is what separates good athletes from great ones." },
  { title: "Lecture on Behavioral Economics", category: "Academic", difficulty: "Advanced",
    transcript: "Behavioral economics challenges the traditional economic assumption of rational actors. Daniel Kahneman and Amos Tversky's prospect theory demonstrated that people evaluate gains and losses differently, with losses weighing roughly twice as heavily as equivalent gains. This asymmetry explains phenomena like the endowment effect, where people value objects they own more highly than identical objects they don't. Richard Thaler's concept of mental accounting shows how people treat money differently depending on its source or intended use, even though money is fungible. These insights have profound implications for policy design." },
  { title: "Documentary: Volcanic Islands", category: "Nature", difficulty: "Intermediate",
    transcript: "Volcanic islands represent natural laboratories for studying evolution and ecology. When a new island emerges from the ocean, it is completely barren. Over time, wind and ocean currents bring seeds, insects, and eventually larger animals. This process of ecological succession can take centuries. The Galápagos Islands, perhaps the most famous volcanic archipelago, inspired Darwin's theory of evolution by natural selection. Each island's unique conditions led to the development of distinct species. Today, these islands face threats from invasive species, climate change, and increasing tourism pressures." },
  { title: "Panel Discussion: Future of Work", category: "Business", difficulty: "Intermediate",
    transcript: "Let's discuss what the workplace will look like in 2030. Remote work is clearly here to stay, but I think the real transformation will come from AI automation. McKinsey estimates that up to 30% of current work activities could be automated by 2030. This doesn't necessarily mean job losses but rather job transformation. Workers will need to continuously upskill and reskill. The most valued human skills will be creativity, critical thinking, emotional intelligence, and complex problem-solving. Companies that invest in employee development will have a significant competitive advantage." },
  { title: "Science Talk: Quantum Computing", category: "Technology", difficulty: "Advanced",
    transcript: "Quantum computing represents a fundamental shift in how we process information. Classical computers use bits that are either 0 or 1, while quantum computers use qubits that can exist in superposition, being both 0 and 1 simultaneously. This enables quantum computers to solve certain problems exponentially faster than classical machines. Current applications include cryptography, drug discovery, and optimization problems. However, quantum computers are extremely sensitive to environmental interference, requiring near-absolute-zero temperatures. Google's quantum supremacy demonstration in 2019 showed a calculation that would take a classical supercomputer 10,000 years completed in 200 seconds." },
  { title: "Radio Program: Music and the Brain", category: "Cultural", difficulty: "Intermediate",
    transcript: "Music has a profound and measurable effect on the human brain. Listening to music activates regions associated with emotion, memory, motor skills, and language processing simultaneously. This is why music therapy has proven effective for patients recovering from stroke, managing chronic pain, and even slowing cognitive decline in dementia patients. The 'Mozart effect,' while often overstated in popular culture, does have a kernel of truth: certain types of music can temporarily enhance spatial-temporal reasoning. Playing a musical instrument is particularly beneficial, as it requires coordination of multiple brain functions simultaneously." },
  { title: "Workshop: Public Speaking Skills", category: "Education", difficulty: "Beginner",
    transcript: "Public speaking consistently ranks among people's greatest fears, but it's a skill that can be developed with practice. The foundation of effective public speaking is preparation. Know your material thoroughly, but don't memorize it word for word. Instead, create a clear structure with key points you want to convey. Body language accounts for over half of your impact on an audience. Make eye contact, use natural gestures, and move purposefully. Vocal variety keeps audiences engaged. Vary your pace, volume, and pitch. Practice with a timer to manage your time effectively. Record yourself to identify areas for improvement." },
  { title: "Lecture on Renewable Materials", category: "Science", difficulty: "Intermediate",
    transcript: "The development of renewable and biodegradable materials is essential for a sustainable future. Researchers are creating alternatives to petroleum-based plastics from sources like corn starch, seaweed, and even mushroom mycelium. These bioplastics can decompose in months rather than centuries. Similarly, bamboo and hemp offer sustainable alternatives to wood and cotton, growing much faster and requiring fewer pesticides. The construction industry is exploring cross-laminated timber as a carbon-storing alternative to steel and concrete. However, scaling these innovations requires significant investment in manufacturing infrastructure and consumer education about proper disposal methods." },
  { title: "Discussion: Social Media Impact", category: "Psychology", difficulty: "Intermediate",
    transcript: "The psychological impact of social media is a subject of intense debate. Research shows that heavy social media use correlates with increased rates of anxiety and depression, particularly among adolescents. The mechanism appears to involve social comparison, where users measure their lives against curated highlights of others. Fear of missing out, or FOMO, drives compulsive checking behavior. However, social media also provides genuine benefits: maintaining long-distance relationships, finding community support, and accessing information. The key seems to be mindful usage. Setting time limits, curating feeds to include positive content, and prioritizing in-person interactions can mitigate negative effects." },
  { title: "Seminar on Data Science", category: "Technology", difficulty: "Advanced",
    transcript: "Data science has emerged as one of the most influential fields in modern business and research. The ability to extract meaningful insights from large datasets drives decision-making across industries. Machine learning algorithms identify patterns that humans might miss, from fraud detection in banking to predictive maintenance in manufacturing. However, the field faces challenges including data quality, reproducibility of results, and the shortage of qualified professionals. Ethical considerations around data collection and use are increasingly important. The democratization of data science tools means that basic analytics capabilities are becoming accessible to non-specialists, while advanced applications still require deep expertise." },
  { title: "Tour Guide: Ancient Rome", category: "Cultural", difficulty: "Beginner",
    transcript: "Welcome to the Roman Forum, the heart of ancient Rome for over a thousand years. This was where political speeches were made, trials held, and religious ceremonies performed. To your right, you can see the remains of the Temple of Saturn, one of the oldest temples in Rome, dating back to 497 BCE. The arch ahead is the Arch of Septimius Severus, built in 203 CE to celebrate military victories. Notice how the ancient street level is several meters below the modern city. Centuries of debris and construction have raised Rome's ground level significantly. The Forum provides a fascinating window into daily life in the ancient world." },
];

const listeningQuestionTemplates = [
  { template: (t: string) => `What is the main topic of this ${t.includes("Lecture") ? "lecture" : "discussion"}?`, options: (t: string) => [`A personal story about ${t.split(":")[1]?.trim() || t}`, `Information and analysis about ${t.split(":")[1]?.trim() || t}`, `A fictional account`, `A product advertisement`], correct: 1 },
  { template: (_: string) => `Which of the following is mentioned as a key point?`, options: (_: string) => ["It is a simple and resolved issue", "There are multiple perspectives to consider", "Only experts should be concerned", "The topic is not relevant today"], correct: 1 },
  { template: (_: string) => `What does the speaker imply about the future?`, options: (_: string) => ["Nothing will change", "Significant changes are expected", "The situation will worsen dramatically", "Technology will solve everything instantly"], correct: 1 },
  { template: (_: string) => `Based on the passage, which statement would the speaker most likely agree with?`, options: (_: string) => ["Simple solutions are always best", "Understanding complexity is important for progress", "Individual action is pointless", "Historical context is irrelevant"], correct: 1 },
];

const writingTopicTemplates = [
  { taskType: "Task 2", topics: [
    "Some people believe that technology has made life more complicated. To what extent do you agree or disagree?",
    "Universities should focus more on practical skills rather than theoretical knowledge. Discuss both views and give your opinion.",
    "The gap between rich and poor countries continues to grow. What are the causes and what solutions can be proposed?",
    "Some argue that arts funding should be reduced in favor of science and technology. Discuss and give your opinion.",
    "International tourism has brought enormous benefits but also problems. Discuss the advantages and disadvantages.",
    "Children today are less creative than previous generations due to technology. Do you agree or disagree?",
    "Governments should invest more in public transportation rather than building new roads. Do you agree?",
    "The best way to reduce crime is to give longer prison sentences. To what extent do you agree?",
    "People are becoming increasingly dependent on technology. Is this a positive or negative development?",
    "Some people think that environmental problems should be solved globally. Others believe local action is more effective. Discuss both views.",
    "Social media does more harm than good to society. To what extent do you agree or disagree?",
    "The traditional classroom will be replaced by online learning within the next decade. Discuss.",
    "Companies have a responsibility to the environment, not just to shareholders. Do you agree?",
    "Many young people today change jobs frequently rather than staying in one career. Why is this happening and is it positive?",
    "Space exploration is a waste of money when there are problems on Earth. Do you agree or disagree?",
    "Advertising aimed at children should be banned. Discuss both views and give your opinion.",
    "All citizens should be required to do community service. To what extent do you agree?",
    "The most important quality of a good leader is communication skills. Do you agree or disagree?",
    "Globalization has led to the loss of cultural identity in many countries. Do you agree?",
    "Health education should be a mandatory subject in all schools. Discuss.",
  ]},
  { taskType: "Task 1", topics: [
    "The graph shows the number of international students enrolled at a university between 2010 and 2023. Summarize the information and make comparisons.",
    "The chart below shows the percentage of household income spent on different categories in two countries. Summarize the key features.",
    "The diagram illustrates the process of recycling plastic bottles. Describe the main stages.",
    "The map shows changes to a town center between 1980 and 2020. Summarize the developments.",
    "The table provides data on employment rates across five sectors over three decades. Analyze the trends.",
    "The pie charts compare energy sources used for electricity generation in 2000 and 2020.",
    "The bar graph shows internet usage rates by age group across four countries. Describe the data.",
    "The flow chart shows how coffee beans are processed from harvest to packaging.",
    "The line graph shows average temperatures in three cities over twelve months.",
    "The diagram below shows the layout of a new shopping center. Describe the key features.",
  ]},
  { taskType: "Essay", topics: [
    "Write about the role of artificial intelligence in education and its potential impact on learning outcomes.",
    "Discuss whether social media platforms should be regulated by governments.",
    "Analyze the impact of remote work on urban planning and community development.",
    "Write about the importance of preserving endangered languages in a globalized world.",
    "Discuss the ethical implications of genetic engineering in food production.",
    "Analyze the relationship between economic growth and environmental sustainability.",
    "Write about the future of healthcare and the role of preventive medicine.",
    "Discuss whether competitive sports have a positive or negative effect on children's development.",
    "Analyze the impact of fast fashion on the environment and society.",
    "Write about the challenges and opportunities of an aging global population.",
  ]},
  { taskType: "Letter", topics: [
    "Write a letter to your local council about a proposed development in your area.",
    "Write a letter to a friend describing your experience studying abroad.",
    "Write a formal complaint letter about a product or service you received.",
    "Write a letter to a potential employer expressing interest in a position.",
    "Write a letter to a newspaper editor about a community issue.",
    "Write a letter to a friend recommending a book, film, or restaurant.",
    "Write a formal letter requesting information about a training course.",
    "Write a letter to a landlord about maintenance issues in your rental property.",
    "Write a thank you letter to someone who helped you in a difficult situation.",
    "Write a letter to your school principal suggesting improvements to the curriculum.",
  ]},
  { taskType: "Report", topics: [
    "Write a report on the effectiveness of recycling programs in your community.",
    "Prepare a report analyzing trends in remote work adoption across industries.",
    "Write a report on the impact of social media on consumer purchasing behavior.",
    "Prepare a report evaluating the transportation infrastructure in your city.",
    "Write a report on the challenges facing small businesses in the current economy.",
    "Prepare a report on the state of mental health services in educational institutions.",
    "Write a report analyzing the growth of renewable energy in your region.",
    "Prepare a report on the effectiveness of current immigration policies.",
    "Write a report on changing dietary habits among young adults.",
    "Prepare a report on the impact of tourism on local communities.",
  ]},
  { taskType: "Task 2", topics: [
    "Some people believe that the internet has made people more isolated. To what extent do you agree or disagree?",
    "Public libraries are no longer necessary because information is available online. Discuss both views.",
    "The government should provide free childcare for all working parents. Do you agree or disagree?",
    "Young people should be required to do unpaid community work in their free time. Discuss.",
    "Nuclear energy is the best solution to the global energy crisis. To what extent do you agree?",
    "Studying history is essential for understanding the present. Discuss both views and give your opinion.",
    "Sports professionals are paid too much compared to other important professionals. Do you agree?",
    "Zoos serve no useful purpose and should be closed. To what extent do you agree or disagree?",
    "The increasing use of surveillance cameras in public places is a positive development. Discuss.",
    "Cultural diversity enriches society but also creates challenges. Discuss both perspectives.",
    "The government should limit the maximum working hours per week. Do you agree or disagree?",
    "Traditional media is being replaced by digital media. Is this a positive or negative development?",
    "International aid does more harm than good. To what extent do you agree?",
    "Schools should teach financial literacy as a core subject. Discuss both views and give your opinion.",
    "The death penalty is never justified. To what extent do you agree or disagree?",
    "Teleworking will completely replace office work in the future. Discuss.",
    "Art and music education is as important as science education. Do you agree?",
    "Single-use plastics should be completely banned worldwide. Discuss both views.",
    "The voting age should be lowered to 16 in all countries. To what extent do you agree?",
    "Happiness is more important than financial success. Do you agree or disagree?",
  ]},
  { taskType: "Task 1", topics: [
    "The charts below show the proportion of male and female workers in six industries. Summarize the key features.",
    "The graph shows CO2 emissions from four different transport types over 20 years. Describe the trends.",
    "The diagram shows how solar panels generate electricity for household use. Describe the process.",
    "The maps show a coastal area before and after a major development project. Describe the changes.",
    "The table shows literacy rates in five developing countries from 1990 to 2020. Analyze the data.",
    "The bar chart compares water consumption in agricultural, industrial, and domestic sectors across three regions.",
    "The line graph shows the number of visitors to three different museums over a five-year period.",
    "The flow chart illustrates the steps involved in manufacturing a smartphone.",
    "The pie charts show household expenditure patterns in a country in 1990 and 2020.",
    "The diagram below shows the water cycle. Describe the main stages of the process.",
  ]},
  { taskType: "Essay", topics: [
    "Discuss the role of public transportation in reducing carbon emissions.",
    "Analyze the effects of screen time on children's cognitive development.",
    "Write about the importance of mental health awareness in the workplace.",
    "Discuss whether tourism is beneficial or harmful to local cultures.",
    "Analyze the relationship between education and economic mobility.",
    "Write about the future of renewable energy and its potential to replace fossil fuels.",
    "Discuss the impact of automation on traditional employment sectors.",
    "Analyze the benefits and challenges of multicultural societies.",
    "Write about the role of technology in modern agriculture.",
    "Discuss whether governments should regulate social media content.",
  ]},
];

const speakingTopicTemplates = [
  { taskType: "Part 1", topics: [
    "Describe your hometown and what you like most about it.",
    "Talk about your daily routine and how it has changed over the years.",
    "Describe a hobby or interest you enjoy in your free time.",
    "Talk about the kind of music you enjoy and why.",
    "Describe your favorite place to eat and what makes it special.",
    "Talk about how you usually spend your weekends.",
    "Describe a skill you would like to learn and why.",
    "Talk about the importance of reading in your life.",
    "Describe a recent trip or journey you have taken.",
    "Talk about your experience with learning languages.",
    "Describe the area where you live and its best features.",
    "Talk about how technology has changed your daily life.",
    "Describe your favorite season and the activities you enjoy during it.",
    "Talk about a type of food that is popular in your country.",
    "Describe your ideal job and what qualities it would have.",
    "Talk about a memorable celebration or event you attended.",
    "Describe how you stay healthy and active.",
    "Talk about your experience with online shopping.",
    "Describe a teacher who had a significant impact on you.",
    "Talk about the role of social media in your life.",
  ]},
  { taskType: "Part 2", topics: [
    "Describe a person who has inspired you. You should say who this person is, how you know them, and why they inspire you.",
    "Describe a book that had a significant impact on you. Include what it was about and why it affected you.",
    "Describe a time when you had to make a difficult decision. Explain the situation and the outcome.",
    "Describe an achievement you are proud of. Say what it was, when it happened, and why it matters to you.",
    "Describe a place you visited that exceeded your expectations. Include what you expected and what surprised you.",
    "Describe a skill you learned that proved very useful. Say what it was and how you learned it.",
    "Describe a time when you helped someone. Explain the situation and how you felt afterward.",
    "Describe an event that changed your perspective on something. Include what happened and why it was significant.",
    "Describe a piece of technology that has made your life easier. Explain what it is and how you use it.",
    "Describe a cultural tradition in your country that you find particularly meaningful.",
    "Describe a challenge you overcame and what you learned from the experience.",
    "Describe your favorite form of entertainment and explain why you enjoy it.",
    "Describe a goal you have set for yourself and the steps you are taking to achieve it.",
    "Describe a memorable journey and what made it special.",
    "Describe a leader or public figure you admire and explain why.",
  ]},
  { taskType: "Part 3", topics: [
    "What are the advantages and disadvantages of living in a city versus the countryside?",
    "How has technology changed the way people communicate with each other?",
    "What role should governments play in addressing climate change?",
    "Do you think education systems adequately prepare students for the modern workplace?",
    "How has the concept of work-life balance evolved in recent years?",
    "What are the implications of artificial intelligence for employment?",
    "Should cultural heritage sites be developed for tourism or preserved in their original state?",
    "How do you think transportation will change in the next 20 years?",
    "What are the benefits and drawbacks of globalization for developing countries?",
    "Do you think social media has made people more or less connected?",
    "How important is it for children to learn about environmental issues at school?",
    "What changes would you like to see in the healthcare system in your country?",
    "Do you think competitive sports are given too much importance in society?",
    "How can communities better support elderly citizens?",
    "What role does art play in society, and should it receive public funding?",
  ]},
  { taskType: "Cue Card", topics: [
    "Talk about a time when you received surprising news. Describe the situation, your reaction, and the outcome.",
    "Describe an important invention from the last century. Explain what it is and why it matters.",
    "Talk about a friend who is very different from you. Describe how you met and what you have in common.",
    "Describe a building or structure you find impressive. Say where it is and what makes it remarkable.",
    "Talk about a time when you tried something new. Describe what it was and whether you enjoyed it.",
    "Describe a movie or TV show that you have watched more than once. Explain why you keep returning to it.",
    "Talk about a time when you were proud of a family member. Describe the situation and your feelings.",
    "Describe an outdoor activity you enjoy. Say how often you do it and what you like about it.",
    "Talk about a time when you had to adapt to a new situation. Describe the challenges and how you coped.",
    "Describe a gift you received that was particularly meaningful. Say who gave it to you and why it was special.",
  ]},
  { taskType: "Discussion", topics: [
    "Discuss the impact of social media on democratic processes and public discourse.",
    "Should university education be free for all citizens? Discuss the implications.",
    "Discuss the ethical considerations of using animals in scientific research.",
    "How can societies balance economic development with environmental protection?",
    "Discuss the pros and cons of allowing employees to work from home permanently.",
    "Should there be limits on free speech? Discuss where the boundaries should be.",
    "Discuss the impact of celebrity culture on young people's values and aspirations.",
    "How can we ensure that technological progress benefits all members of society equally?",
    "Discuss the role of traditional medicine alongside modern healthcare practices.",
    "Should governments prioritize space exploration or solving problems on Earth? Discuss.",
  ]},
  { taskType: "Part 1", topics: [
    "Talk about a type of exercise you enjoy doing regularly.",
    "Describe your favorite way to relax after a busy day.",
    "Talk about a place in your city that you visit often.",
    "Describe the type of weather you prefer and why.",
    "Talk about a skill you are currently learning or improving.",
    "Describe your favorite childhood memory.",
    "Talk about the importance of family traditions in your culture.",
    "Describe a recent movie or show that impressed you.",
    "Talk about the kinds of books or articles you like to read.",
    "Describe how your neighborhood has changed over the years.",
  ]},
  { taskType: "Part 2", topics: [
    "Describe an older person you know and admire. Say who they are and what makes them special.",
    "Describe a situation where you had to work as part of a team. Explain the outcome.",
    "Describe a place in your country that every visitor should see. Say what makes it unique.",
    "Describe a time when you had to learn something quickly. Explain what it was and how you managed.",
    "Describe a gift you gave someone that made them very happy. Say what it was and why you chose it.",
  ]},
  { taskType: "Part 3", topics: [
    "How can schools better prepare students for the challenges of adult life?",
    "What are the pros and cons of living in a multicultural society?",
    "How has the role of women in the workforce changed in recent decades?",
    "What impact does advertising have on consumer behavior?",
    "How important is it for young people to travel and experience other cultures?",
  ]},
  { taskType: "Cue Card", topics: [
    "Talk about a historical event that you find fascinating. Describe what happened and why it interests you.",
    "Describe a food from your country that you would recommend to a foreigner. Say what it is and how it is prepared.",
    "Talk about a time when you faced a fear. Describe what happened and how you felt afterward.",
    "Describe a public place in your city that needs improvement. Say what changes you would suggest.",
    "Talk about a song or piece of music that has special meaning to you. Describe why it is important.",
  ]},
  { taskType: "Discussion", topics: [
    "How has the rise of e-commerce affected traditional retail businesses?",
    "Should parents monitor their children's internet usage? Discuss.",
    "What are the long-term effects of urbanization on the environment?",
    "How can technology be used to improve education in rural areas?",
    "Should cultural traditions be preserved even when they conflict with modern values? Discuss.",
  ]},
];

export async function seedDatabase() {
  const existingReading = await db.select().from(readingPassages).limit(1);
  if (existingReading.length > 0) return;

  console.log("Seeding database with 100 items per module...");

  for (const topic of readingTopics) {
    const [passage] = await db.insert(readingPassages).values({
      title: topic.title,
      content: topic.content,
      difficulty: topic.difficulty,
      category: topic.category,
      examType: "ielts",
      timeLimit: 15,
    }).returning();

    const questionSet = readingQuestionTemplates.map((qt, idx) => ({
      passageId: passage.id,
      questionText: qt.template(topic.title),
      questionType: "multiple_choice",
      options: qt.options(topic.title),
      correctAnswer: qt.options(topic.title)[qt.correct],
      explanation: `The correct answer relates to the key information presented in the passage about ${topic.title.toLowerCase()}.`,
      order: idx,
    }));

    await db.insert(readingQuestions).values(questionSet);
  }

  for (const topic of listeningTopics) {
    const [passage] = await db.insert(listeningPassages).values({
      title: topic.title,
      transcript: topic.transcript,
      difficulty: topic.difficulty,
      category: topic.category,
      examType: "ielts",
      duration: 180,
    }).returning();

    const questionSet = listeningQuestionTemplates.map((qt, idx) => ({
      passageId: passage.id,
      questionText: qt.template(topic.title),
      questionType: "multiple_choice",
      options: qt.options(topic.title),
      correctAnswer: qt.options(topic.title)[qt.correct],
      explanation: `This answer is supported by the content of the listening passage.`,
      order: idx,
    }));

    await db.insert(listeningQuestions).values(questionSet);
  }

  let writingCount = 0;
  const difficulties = ["Beginner", "Intermediate", "Advanced"];
  for (const group of writingTopicTemplates) {
    for (const topic of group.topics) {
      await db.insert(writingPrompts).values({
        title: `${group.taskType}: ${topic.substring(0, 60)}...`,
        promptText: topic,
        taskType: group.taskType,
        difficulty: difficulties[writingCount % 3],
        examType: "ielts",
        minWords: group.taskType === "Task 1" ? 150 : 250,
        maxWords: group.taskType === "Task 1" ? 200 : 350,
        timeLimit: group.taskType === "Task 1" ? 20 : 40,
      });
      writingCount++;
    }
  }

  let speakingCount = 0;
  for (const group of speakingTopicTemplates) {
    for (const topic of group.topics) {
      await db.insert(speakingPrompts).values({
        title: `${group.taskType}: ${topic.substring(0, 60)}...`,
        promptText: topic,
        taskType: group.taskType,
        difficulty: difficulties[speakingCount % 3],
        examType: "ielts",
        preparationTime: group.taskType === "Part 2" || group.taskType === "Cue Card" ? 60 : 15,
        responseTime: group.taskType === "Part 1" ? 60 : 120,
      });
      speakingCount++;
    }
  }

  console.log(`Seeded: ${readingTopics.length} passages (${readingTopics.length * 4} questions), ${listeningTopics.length} listening passages (${listeningTopics.length * 4} questions), ${writingCount} writing prompts, ${speakingCount} speaking prompts`);
}
